name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    # Pour ne déclencher le workflow que si le dossier "backend" a été modifié :
    paths:
      - "src/backend/**"

env:
  REGISTRY_URL: "exo.container-registry.com"
  NAMESPACE: "c213-emf" # Adapté en fonction de votre registry
  IMAGE_NAME: "todo-app-beer" # Nom de l'image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: quentin.badoud@edufr.ch
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} src/backend/
        # Remarque : Assurez-vous que le Dockerfile se trouve dans le dossier "backend"

      - name: Tag Docker image for registry
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ env.REGISTRY_URL }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image to registry
        run: |
          docker push ${{ env.REGISTRY_URL }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
